### PR TITLE
ELEC-211: Driver Controls Carrier layout

### PR DESCRIPTION
**Pull request by Grenite**
Work related to carrier board is now being done in this branch. The latest revision should have applied the requested changes from last Thursday. That is including:
- Use a pour for 3V3 and 12V pads as multiple pins are used for each net
- Directly connect traces to pads (Don't use less than 90 degree angles)
- Add 2 pin ultrafit connector for 12V (Pin 1 = 12V, pin 2 = GND)
- Add mounting holes, move passives to bottom layer if necessary
- Double check that U1 is within height limits
- Move controller board so CAN connectors are facing outwards
- Move designators so they are visible and do not intersect other silkscreen
- Add pinout table for connectors P2, P3, P4, P5, P6 on bottom silkscreen
- Remove thermal relief on stitching vias, add more stitching vias

The exception is the vertical headers part, I'll make sure all the connectors are vertical in the next commit.

### CODE REVIEW

**Comment by tituschow** [comment]
- [ ] Add silkscreen labels for connectors - super brief, just get an idea of what the connector's for
- [ ] Make sure none of the pins conflict with debug LEDs or other reserved pins

**Comment by taipingli** [comment]
July 13 Board Review Notes
- [ ] Move top connectors for clearance 
- [ ] Label +12V connector
- [ ] Add power LED
- [ ] Add test points for I2C, GND
- [ ] Make all labels in caps
- [ ] Push P7 up to avoid controller board keep out

**Comment by Grenite** [comment]
- [ ] PA0 is shorting with PA1 in the gerber creation, improve the spacing between the two nets to prevent this from happening

**Comment by tituschow** [comment]
So we're looking at using a [multiturn encoder](http://www.bourns.com/docs/Product-Datasheets/AMM20B.pdf) for the steering angle sensor instead of a magnetic sensor. To accommodate this change, I suggest:
- [ ] Add a 5V LDO to supply the sensor
- [ ] Replace the previous steering angle sensor connector with a 4-pin DuraClik (5V, GND, Analog out)
- [ ] Use a resistor divider + buffer to convert the reading to 3V and use the controller board's internal ADC.

@KevinHQChen @taipingli Thoughts?

**Comment by Grenite** [comment]
- [ ] Separate the lines of text on the table on the back over and try aligning them better
- [ ] If required, remove the table lines
- [ ] Remove excess GND stitching vias, add GND stitching vias on isolated areas around mezzanine 
- [ ] Double check m2.5 head clearances (Will use 6mm diameter keepout) 
- [ ] For the encoder analog, make sure it does not interfere with other pins such as the debug LEDs

**Comment by taipingli** [comment]
- [ ] Add RC circuit to output of buffer incase we want to do filtering
- [ ] Move components out a bit so the controller board can fit without conflicts 
- [ ] Remove keep out around the mounting holes
- [ ] Add stiching vias
e.g. 
image
- [ ] Move the right most trace to the left to avoid cutting the ground plane so much
image

**Comment by tituschow** [comment]
Schematic:
- [ ] Clean this up
image
- [ ] Use multiple harnesses instead of trying to stretch this one out (see power distribution)
- [ ] Try to align your connectors
- [ ] Try to align your text

PCB:
- [ ] Don't use regions to bypass thermal relief
- [ ] Fix collision with controller board
image
- [ ] Add silkscreen to your test points explaining what they're for
- [ ] Add silkscreen for LED1 explaining what it's for

**Comment by taipingli** [comment]
- [ ] Check with BMS_AFE or Power Distribution for the RC circuit. It should've been the 10000pF capacitor instead of 0.1uF. 
- [ ] If we rearrange PB0, PB1, PB2, I think it may help your routing a lot? Then you can also avoid cutting the ground plane so much
image
- Put stiching vias in places where they are actually needed
e.g. 
image
- Align your text both vertically and horizontally with align (Ctrl-Shift-L, R, T, B), perhaps remove the grid and see how that looks
image

**Comment by taipingli** [comment]
- [ ] You have clearance violations at 2 vias, please run a DRC and fix those accordingly. 
- [ ] Make sure your keep out outline is >0.6mm, Elecrow specifies a minimum of 0.3mm from the edge to the traces
- [ ] For test points, you should include the test point designator as well as the label (TP1 GND, etc) 
- [ ] Also make sure you have the designator for the LED

**Pull request merged**
