### PR TITLE
ELEC-212: Driver Controls Peripheral Board

### PR DESCRIPTION
**Pull request by Grenite**
Work related to the peripheral board is now being done in this branch. The changes requested from last Thursday should be applied, that is including:
- Make sure P2 matches pedal pinout
- Fix grid spacing for library components (10 mil), fix schematic aesthetics to match style guide
- Remove unnecessary connector (the 4 pin one)
- Ensure the magnetic sensor has enough clearance, move it to its own side
- Remove thermal relief on stitching vias
- Add LDO from controller board to power ADC with 3V, add 1uF bulk cap to 3V3 input

### CODE REVIEW

**Comment by taipingli** [comment]
July 13 Board Review
- [ ] Change all labels to caps
- [ ] Change U1 such that pin 1 is on the top left
- [ ] Change AN0 -> POT1
- [ ] Add power LED (check controller board for RES value)
- [ ] Get rid of most stitching vias, just ensure that you have a good return path
- [ ] Check if mounting holes have enough clearance

**Comment by Grenite** [comment]
- [ ] Switch the positions of the two 6 pos duracliks
- [ ] Update libraries from master, fix the connections accorindgly
- [ ] Change label for "Carrier" to something more specific like "Driver Controls Carrier"
- [ ] Double check m2.5 screw head size, enlarge the board if necessary to allow clearance for screws

**Comment by taipingli** [comment]
- [ ] Add RC circuit to output of buffer incase we want to do filtering
- [ ] Move components out a bit so the controller board can fit without conflicts 
- [ ] Remove keep out around the mounting holes
- [ ] Add stiching vias
e.g. 
image
- [ ] Move the right most trace to the left to avoid cutting the ground plane so much
image

**Comment by taipingli** [comment]
- [ ] Label your LED with silkscreen (e.g. PWR, POWER)
- [ ] Get rid of the keep outs on the mounting holes, only use it as a guide but not in your final layout
image
- [ ] Consider moving the magnetic sensor to the edge of the board? @tituschow

**Comment by tituschow** [comment]
Can you update your block diagram and revision number?

**Comment by taipingli** [comment]
- [ ] Keep your designators there for the LED

**Comment by taipingli** [comment]
If you swap Pot 1 and Pot 2, should'nt that make layout a lot easier? 
image

Also, try and align and center your silkscreen whenever possible, it'll make the board look a lot cleaner.

**Comment by taipingli** [comment]
- [ ] Align the designators on the top of the top layer, you can use the align function built in to do so.

**Comment by taipingli** [comment]
Your gerbers are missing a few layers. Please check the elecrow requirements and instructions and regenerate them.

**Pull request merged**
