### PR TITLE
ELEC-269 Controller Board Rev 6.0

### PR DESCRIPTION
**Pull request by taipingli**
- Switched from OSC32_IN/OUT to OSC_IN/OUT to utilize HSE
- Aligned silkscreen on PCB

Note: No changes to pads, stencil will remain the same.

### CODE REVIEW

**Comment by tituschow** [comment]
Do we still need the PC14/PC15 nets?
Maybe organize the power supply doc or move it to the main doc since it seems pretty empty :P

**Comment by tituschow** [comment]
@ckitagawa - Do you mind defining a few pins for PWM so @taipingli can adjust the nets appropriately?

**Comment by ckitagawa** [comment]
These are only outputs because I don't think we have any PWM inputs. At least we don't have a driver for it yet. Each timer outputs on all the pins it is tied to in the same way so it doesn't matter which pin we use.

So these pins are all free. We probably only need one for each timer unless we plan to run connectors to multiple fans or something that use the same speed?
PA8 or PA9 or PA10: PWM_TIM1
PB0 or PB1: PWM_TIM3

These PWM_TIM* are all connected to other things already. Mostly UART or SPI. Just pick whichever is more convenient or less intrusive and add it to the hardware schematic. I'll update my AltFn PR to represent the changes.
PA4: PWM_TIM14 (Already used for something though)
PA2 or PA3: PWM_TIM15 (Both of these are already used for something else though)
PA6 or PB8: PWM_TIM16 (Both of these are already used for something else though)
PA7 or PB9: PWM_TIM17 (Both of these are already used for something else though)

**Comment by taipingli** [comment]
PA8, PB0, and PA4 are assigned to PWM channels now. @ckitagawa will 3 be enough? I'm thinking our main use case would just be for fans?

**Comment by Yifei-Li** [comment]
Ground loop at Y1 ground pads and clock trace long. For best results, rotate oscillator and shift capacitors to optimize for oscillator trace length.

**Comment by taipingli** [comment]
@Yifei-Li Could you take a look at the layout before we send it out this weekend?

**Pull request merged**
