### PR TITLE
ELEC-197: Driver Controls Schematic

### PR DESCRIPTION
**Pull request by Grenite**
Added the schematics for the connectors and debouncing circuits, a generic inverting schmitt trigger was added to the schematic library as a placeholder component until the final schmitt trigger component is decided. Resistor values are TBD until the LED and schmitt trigger are decided. The push-to-talk button will be changed so that it is a regular signal input instead.

### CODE REVIEW

**Comment by taipingli** [comment]
Please make sure to read up on the hardware styling guide on [Confluence](https://uwmidsun.atlassian.net/wiki/display/ELEC/Hardware+Style+Guide). 

##Notable things from this schematic: 
- [ ] Utilize the 10mm snap grid and align all components/pins to grid
- [ ] Use CamelCase for all naming (capital letter for all words, including the first word
- [ ] Use Dura-Clik connectors for signals, be sure that we can buy them from Mouser/Digikey with a IPA mating connector
- [ ] I recommend using harnesses instead of the sheet symbol to go between sheets. The sheet symbol may be better used to draw a block diagram
- [ ] Delete unused nets from the harnesses
- [ ] I recommend using ground power ports rather than connecting all of them together with a long. Makes it easier to read. 
image
- [ ] These should all be aligned to each other 
image
- [ ] You should label all your connectors, just add a text string below/beside to say what they're for

## General Things: 
* What's the justification for using just the GPIOs without any expanders or anything? This could make wiring a lot more complex
* If we do use an expander, then debouncing probably could be done in software instead. Consult with @tituschow and @Derpalooza 
* You should include any changes to any of the libraries to your commit messages. See my commits to the Power Distribution PR #15 , or Kevin's commits to the BMS AFE PR #17 .

**Comment by Grenite** [comment]
The latest commit should have completed the requested changes, also the button debouncers should be removed as it is no longer needed. I added a second project under MSXII_steeringWheel which will host the steering wheel board. An i2c gpio io expander MCP23008 is used with the IO as it appears sufficient enough for our needs.

**Comment by taipingli** [comment]
## Schematic Changes
### Carrier Board
- [ ] Rename your nets on the mezzanine interface. Something good would be for example, PA01_Headlights
- [ ] Rename your project and files to follow the convention. driverControls should be DriverControls, same with all nets in your schematics
- [ ] Unless you have any reason to, switch to a 2 pin duraclik for power (P2) 
- [ ] Get rid of nets in the mezzanine interface that you're not using
- [ ] Consider using a resistor array for multiple pull ups

### Steering Wheel Board
- [ ] Look at the other ICs in our schematic library and follow how they are created. Try to have power on top, GND on bottom, inputs on the left and outputs on the right. Also make sure to have the pin names as well. 
- [ ] Check if you need P3, seems to just be grounded right now. 
image

## Visual Changes

- [ ] Make sure you follow a 10mil grid (As per standards)  and align everything to it
e.g. 
image

**Comment by tituschow** [comment]
You need pullups on your I2C lines.

What is this for? Why does it live on the steering wheel board?
image

You need at least a connection to GND. Why are regen high and low two different inputs?
image

**Comment by Grenite** [comment]
The appropriate revisions should be in the latest commits. I also pulled from master to update the altium libraries.

**Comment by tituschow** [comment]
You didn't answer my questions and still have connectors that seem to have no purpose.

**Comment by Grenite** [comment]
I thought this was talked about before. The CPC1017 is the solid state relay which will be used for the push-to-talk bypass. I wasn't given how the push-to-talk works on the radio so it live on the board until I have further info. Also the REGENHIGH and REGENLOW was inputs specified to me from Kevin. I do not know which connectors you find have no purpose. Can they be pointed out?

**Comment by tituschow** [comment]
No, you never gave me an answer. PTT is an input. The relay should not be on the steering wheel. How would that work in implementation? I told you that yesterday in person.

How is the regen selector supposed to work? What was the rationale?

You have a connector that is almost completely grounded and a bunch of NCs on P4. You're also missing 12V in.

**Comment by Grenite** [comment]
I'm not sure about the PTT, I don't have enough info about our radio system until I can make a fully proper implementation, so I left with the relay that you have suggested before until I get more information about our radio. From what I was told, there are two buttons to increment and decrements the regenerative braking strength respectively. That's what I was told. The grounded connectors are to connect the switches as they will function as pull down switches on closed. I also do not know any other duraclick isl connectors that are 5 positions so I just used the 8pos connector instead and left the excess pins unused, I should have replaced them with GND pins instead. Where is the 12 input missing? I only used what was needed from the boards.

**Comment by tituschow** [comment]
PTT should not be on the steering wheel.

If that's the case, your net names for adjusting regen brake strength are unclear. Please update them to make it more obvious what they're for. @KevinHQChen @taipingli - How is regen braking strength adjustment supposed to work?

Why do you need an entire connector for ground? P3 on both boards is oversized.

All carrier boards must have a 12V input. See the hardware style guide.

**Comment by Grenite** [comment]
Sure, I can move the PTT off the board and change the net names. But I should have explained the grounded connectors already, they're for the switches as they will function as pull down switches. The connector is there so I their wires can be connected to the board. 
I am unclear how you want the boards to be. Do you want the steering wheel board to be a carrier board? Or an extension of the Center Console command board? Each choice will have very different implementations.

**Comment by tituschow** [comment]
Please explain how that would work.

**Comment by Grenite** [comment]
I do not know. I appear to lack the idea of what you want from the driver control board.

**Comment by tituschow** [comment]
Please explain how you understand it to work.

**Comment by taipingli** [comment]
I was thinking of using a rotary selector for regen strength, for off, low and high. Alternatively, a binary switch of low and high regen strength should be ok as well. 

Regarding push to talk, I think we should make it so that it can be either active high or active low, and just use 0 Ohm jumpers to select either for this revision. If you have the time you could also look into different radio options and how their PTT works. 

The steering wheel board should be mostly passives, other than the GPIO expander. The purpose of the expander is just to reduce complexity and the number of wires we have to run through the clock spring. Keep in mind that that's our main limitation for wiring.

**Comment by Grenite** [comment]
There is one carrier board, and a steering wheel board: There are multiple panel-mounted buttons + one bms fault LED that are for the center console, they are connected to the carrier board. Then there is a steering wheel board that handles another set of buttons. The information of the steering wheel buttons will be handled by a GPIO expander. The expander connects to the carrier board through the connectors.

**Comment by Grenite** [comment]
@taipingli Would the active high/active low on the PTT be for the input or output? I believe regardless of the choices, they can be configured in the software.

**Comment by tituschow** [comment]
If you're using a relay, why does it matter? You're just shorting two wires.

**Comment by Grenite** [comment]
If the radio just needs to short a connection to activate then that's fine. A relay is all we need. It matters because I do not even know how the radio operates its PTT function.

**Comment by tituschow** [comment]
It's always some form of short. Either mic - PTT - mic ground, enable - PTT - gnd, or enable - PTT - vcc.

**Comment by tituschow** [comment]
In your model that you've just explained, please explain how your [previous comment](https://github.com/uw-midsun/hardware/pull/21#issuecomment-310480178) would work.

**Comment by Grenite** [comment]
Then should we use a relay then?

**Comment by tituschow** [comment]
You're already using a relay.

**Comment by Grenite** [comment]
Does already using a relay mean we should use a relay? I believe it should have explained it already, but it works by the driver pressing the desired switches, and then the switches are read. The controller behaves as it is programmed.

**Comment by tituschow** [comment]
Like, you've already specced a relay. You have a relay in your schematic.

No, I'm asking how the connectors play into this. How would this work electrically? I know how digital inputs work.

**Comment by Grenite** [comment]
The connectors connect the switches since they're panel mounted. The switches connect the respective I/O pin the GND since the switches will function as a pull-down switch.

**Comment by tituschow** [comment]
The steering wheel board will have the buttons/switched designed into the PCB. Even if they weren't (i.e. for the carrier board), you only need a single ground. You don't need a whole connector for it.

What's the purpose of PTT in and out? Please explain your understanding of how PTT will work and how it is wired.

You do not need an 8-pin connector for 5 wires. (P1)

**Comment by tituschow** [comment]
image

Outputs are push-pull. You should not connect pullup/down resistors to outputs.

**Comment by Grenite** [comment]
It would have certainly helped out much better if I knew the buttons were to be pcb mounted on the steering wheel board. 
Also, PTT has an in and out because one is a regular input, the output is then controlled through the controller board. 
Also, I picked an 8 pin connector because duraclik 5 pin connectors lack an available ISL mating connector. Unless you can find one I will be using the 8 pin connectors.
Also please point out which pins are outputs. Of all the pins you have displayed, only LED_OUT will function as the the output.

**Comment by tituschow** [comment]
As I mentioned before, we are not robots and can not tell you everything you'll ever need to know on the spot. That's why we're always available for you to ask us questions.

Please explain how PTT would work with that model.

There are many other connectors, such as 2 and 6 pin ISLs. As I mentioned before, you can find them on Molex's site.

LED_OUT is an output. Please think about what I said.

**Comment by Grenite** [comment]
It appears that we have very different ideas on how the board should be designed. If you need clarification, PTT works by being treated as a regular input. The controller board takes the input, and then outputs it via PTT-out. That output is then controlling the relay to short the PTT to bypass. Yes I am aware that there are ISL connectors on MOLEX's website. But are we ordering directly from them? If we're looking for ISL connectors on Digikey, they only got the 8pos housing in stock. I was using different sized connectors such as the 15pos, 7pos and 6pos, but you told me the ISL's weren't available.
What about LED_OUT? I do not understand where you are getting this from.

**Comment by tituschow** [comment]
No, we shouldn't have different ideas. If we do, then this is the time to align them.

PTT in is on the steering wheel. That makes sense. Why is PTT out on the steering wheel? Why go through the extra trouble?

We order components primarily from digikey or mouser, but will order from other places if needed. Again, if you needed to clarify that, you should've asked us.

LED_OUT is an output. You have attached a pulldown to it.

**Comment by Grenite** [comment]
PTT-out was on the steering wheel was for driving the relay. I do not see the extra trouble here when it was just one I/O that was used. Also the LED_OUT had a pull_down resistor because it was to provide discharge path for the MOSFET gate. Otherwise, the capacitance on the MOSFET gate would cause unexpected behavior when the output is not driven HIGH. Also I will be aware of the potential suppliers next time.

**Comment by tituschow** [comment]
We need to run our wires through a clockspring/the steering column. We've already said that we're minimizing the number of wires. Where is the PTT out supposed to go?

The MCU output is push-pull.

**Comment by Grenite** [comment]
PTT out was supposed to go the relay, but since it will be moved out the PTT-out is also being moved accordingly. Also if you really want to remove the pull-down resistor, then I can do that, but what I was doing was not ideal anyways, according to the link: https://electronics.stackexchange.com/questions/68748/question-about-mosfet-gate-resistor

**Comment by Grenite** [comment]
Things to complete for next revision
- [ ] Merge libraries from master
- [ ] Check the master libraries for any potential reusable components
- [ ] For added components by me, ensure the full list of parameters are in the schematic libraries according to link: https://uwmidsun.atlassian.net/wiki/spaces/ELEC/pages/9306201/Libraries+and+Component+Creation
- [ ] Move LED over from Carrier to Steering Wheel board
- [ ] Label the i2c nets with someting like GPIO_SCL or STEERING_WHEEL_SCL
- [ ] Net names don't have to be abbreviated, so change them to full names
- [ ] The relay resistor is at an incorrect value, replace it with a proper 2.2K resistor
- [ ] Add a decoupling cap to the Vdd of the GPIO expander
- [ ] Reduce the right angle connections on the wiring for simplification
- [ ] Add text to the connectors on the carrier board to specify their purposes

**Comment by KevinHQChen** [comment]
- [ ] Net labels need to match mezzanine labels, stick to using the mezzanine labels for these signals
image
- [ ] There are still compiler errors, please ask me if you don't know how to get rid of them.
- [ ] remove unused mezzanine signals, the black arrows are unncessary, just use a text string, also there's no need to add a text string that says the exact same thing as the net label
image
- [ ] Label all connectors (how do I know where this connector is going?)
image
- [ ] Select ergonomic board-mount switches to replace these stand-ins
image
- [ ] No need to make digikey PN visible, use existing components in library as reference
image

**Comment by taipingli** [comment]
June 29 Board Review Notes
##Steering Wheel Schematic
- [ ] I2C net naming
- [ ] Move the top right connector to the left of the GPIO expander and connect directly if possible
- [ ] Extend wires past net names (SCL, SDA, BMS_FAULT_SIGNAL, etc) 
image
- [ ] Move resistor array's text to have a larger margin
- [ ] Change R4 for resistor to 510R
- [ ] Q1, check if the GPIO expander can source/sink enough current. Can delete it if it can. 

## Carrier Board
- [ ] Add net labels to all wires
- [ ] Add a connector for the steering angle sensor (I2C)
- [ ] Update all parts from library, and fix library links
- [ ] Align everything to a 10mil grid
- [ ] Update steering angle + pedal connectors to remove external interrupt lines (leave 1 for pedal)
- [ ] Put pedal board on other I2C bus

**Comment by tituschow** [comment]
Please fix this.
image

The standard for no connect is NC. If you're only using 4 pins, please use a 4-pin connector. Also, this should be going to the steering angle sensor, not the steering wheel. Please change the text to match. You probably don't need to have "board". Same goes for the pedal board.
image

This seems a little tight.
image

Your PCB for driver controls is huge. Please try to make it smaller.

**Comment by KevinHQChen** [comment]
July 6th, 2017 Driver Controls Layout Review

- [ ] Checkout layout-related files into separate branch

- [ ] Use a pour for 3V3 and 12V pads as multiple pins are used for each net

- [ ] Directly connect traces to pads (Don't use less than 90 degree angles)

- [ ] Add 2 pin ultrafit connector for 12V (Pin 1 = 12V, pin 2 = GND)

- [ ] Add mounting holes, move passives to bottom layer if necessary

- [ ] Double check that U1 is within height limits

- [ ] Move controller board so CAN connectors are facing outwards

- [ ] Move designators so they are visible and do not intersect other silkscreen

- [ ] Add pinout table for connectors P2, P3, P4, P5, P6 on bottom silkscreen

- [ ] Remove thermal relief on stitching vias, add more stitching vias

July 6th Driver Peripherals Schematic/Layout Review

- [ ] Checkout related files into its own branch

- [ ] Make sure P2 matches pedal pinout

- [ ] Fix grid spacing for library components (10 mil), fix schematic aesthetics to match style guide

- [ ] Remove unnecessary connector (the 4 pin one)

- [ ] Ensure the magnetic sensor has enough clearance, move it to its own side

- [ ] Remove thermal relief on stitching vias

- [ ] Add LDO from controller board to power ADC with 3V, add 1uF bulk cap to 3V3 input

**Comment by tituschow** [comment]
- [ ] Add mounting holes
- [ ] Use vertical headers for everything

**Comment by Grenite** [comment]
Work now being moved into two separate branches: ELEC-211 and ELEC-212 respectively.

**Pull request closed without merging**
