### PR TITLE
ELEC-312 Solar Sense Slave Schematic & PCB

### PR DESCRIPTION
**Pull request by plguo**
* Create the schematic for solar sense slave
* Add a digital isolator
* Add a class D audio amplifer

Schematic Library
* IC AUDIO AMPLIFIER TPA2005D1
* IC DIGITAL ISO SI8715BC-A-IS
* RES 220 OHM 1% 1/10W
* RES 820 OHM 5% 3/4W 2010
* ~CONN 12POS HEADR FEMALE 0.1"~

PCB Library
* IC CLASS D AUDIO AMPLIFIER TPA2005D1 8-MSOP

### CODE REVIEW

**Comment by Yifei-Li** [comment]
- [ ] change the regulator to the one used in AFE
- [ ] resize MPPT_HV voltage divider

**Comment by taipingli** [comment]
What's the difference between ISO_3V3 and SLAVE_3V3? Also how much current are we drawing from the 3.3V LDO? Might want to do some thermal calculations to make sure it works for this purpose

**Comment by plguo** [comment]
The ISO_3V3 (will be ISO_5V after addressing Yifei's comment) is supplied by the MPPT and the regulator. The SLAVE_3V3 is supplied by the LIN controller board.

The total current drop of the isolated side (an op-amp, an audio amplifier and a digital isolator) is around than 8.9 mA, which is within the range of the DC-DC converter and the voltage regulator.

**Comment by tituschow** [comment]
- [ ] Add harness for LIN controller
- [ ] Need to ensure through hole TPs have a footprint linked to them or use SMT TPs
- [ ] Annotate components
- [ ] Check values of RC on the regulator input - used for transient protection? Ensure that system current is less than the resistor value
- [ ] Ensure that ISO_[x] is on the same side - I believe most of our boards use ISO_[x] to refer to the LV side.
- [ ] Remove MPPT_HV, +6V LEDs
- [ ] Use different symbol for slave ground
- [ ] Use more obvious net names - not clear which side is which (LV/HV)
- [ ] Add block diagram
- [ ] Net names should be ALL_CAPS
- [ ] Add decoupling for the amp
- [ ] Look into using 3V LDO to remove noise from the opto supply instead of a bunch of caps or look into alternate values

**Comment by tituschow** [comment]
Can you make sure your block diagram is the first sheet and remember to update your sheet numbers + revision?

Additionally, your block diagram is missing the 3V LDO. You should be explicit with your net name that this is a 3V supply (instead of `DIGITAL_ISO_VDD`).

For your testpoints, your designator should be TPx, not TH_TPx. Also, if you can't use overbars to denote active-low signals, we use `n` as a prefix to denote active-low instead.

Looking at precharge controller, it seems like we've using isolated to refer to the HV side before. However, I see that you've marked which side is considered "isolated" and it seems to make sense. @taipingli any thoughts?

Your 3V LDO should be powering all of your analog circuits so they're all referenced from the same supply. You should make sure you have decoupling caps by all of your IC supply pins.

Have you tested the 1M/140k resistor divider? That seems very high.

**Comment by plguo** [comment]
@tituschow No sure which active-low signals are you thinking about. I haven't tested the voltage divider but I calculated the voltage divider output range based on the MPPT output range.

**Comment by tituschow** [comment]
In your voltage sense power supply, you have a test point for `nRESET`.

Can you add a test point for the output of the 3V LDO?

**Comment by tituschow** [comment]
- [ ] Rename `ISO_3V` to `ISO_LDO_3V`
- [ ] Add 1uF decoupling cap to opto
- [ ] Check if there should be a resistor in the path of `nSHUTDOWN`
- [ ] Add bottom ground plane
- [ ] Add more clearance for HV stuff
- [ ] P3 should be an UltraFit
- [ ] Add 12V connector for controller boards
- [ ] Add silkscreen for connectors and their pins
- [ ] Add mounting points

**Comment by tituschow** [comment]
Just so you know, your bottom ground plane on the LV side isn't very useful right now because it's cut by the 3V trace.

- [ ] Add silkscreen for each pin of the connector - see power distribution for example
- [ ] Move board name silkscreen so that it's visible when the controller board is on top

**Comment by taipingli** [comment]
Couple of changes: 
- [ ] Use the normal test points for everything on the non-isolated side. Don't really need through hole ones there. 
- [ ] Route traces so they go from power -> capacitor -> component. Instead of power -> component -> capacitor. Change it so they're like this
image
Also do this for U4, U6, 
- [ ] Make sure traces go out from either the middle of the pad or the corner. 
image
- [ ] Maybe route MPPT_HV like this so it's not cutting the bottom plane up as much?
image
- [ ] Try using vertical traces instead of having an acute angle between the pad and the trace
image
- [ ] Use all caps for the silkscreen (MSXII SOLAR SENSE SLAVE REV 1.XX) 
- [ ] We got rid of some of the 0 ohm or test points on AFE, could you do the same changes to the power supply?
image

**Comment by taipingli** [comment]
Looks good @plguo . One minor thing is to just add a few stitching vias between the 2 ground planes (top and bottom for both GND and HV_GND). Maybe just 4 or 5 in total in the empty copper areas, nothing crazy. Basically to connect the top and bottom nicely.

**Pull request merged**
