### PR TITLE
ELEC-102: Updated Carrier Template

### PR DESCRIPTION
**Pull request by tituschow**
Added DRCs, generated .RUL file, added 3D models for bergstak plug + receptacle.

Please double-check my DRCs and make sure the template project is okay. I've replaced the template SchDoc's revision number with a project parameter.

### CODE REVIEW

**Comment by taipingli** [comment]
Looks pretty good. Could you make a few small changes? 
- [ ] Update schematic template from the actual template
- [ ] Change max width of traces to something wider
- [ ] Make sure all of [these](https://www.elecrow.com/wiki/index.php?title=Q%26A_for_PCB_service) rules are included

**Comment by tituschow** [comment]
I used that page to make my DRCs.

**Comment by taipingli** [comment]
Do we also want to make a note of which IOs are being used for debugging and any other purposes on the controller board? Adding the ADCs to the nets would be nice too, e.g PA0/ADC0 @tituschow

**Comment by tituschow** [comment]
Yeah, that sounds like a good idea. I'll add it to the mezzanine.

**Pull request merged**
