### PR TITLE
ELEC-308 LIN Controller Board

### PR DESCRIPTION
**Pull request by menalabib**
- Created schematic/footprints for:
IC MCU 32BIT 32KB FLASH 20TSSOP
IC MCU 32BIT 32KB FLASH 28UFQFPN
IC LIN  TRANSCEIVER TLE7257LE
CAP CER 220PF 50V 5% X7R 0603
RES 2.4K OHM 1% 1/10W 0603
CONN 12 POS HEADER MALE 2x6

### CODE REVIEW

**Comment by Yifei-Li** [comment]
Move LIN_EN to PA15 or something

**Comment by Yifei-Li** [comment]
Flip the long ass connectors to the other side

**Comment by Yifei-Li** [comment]
- [ ] dim LEDs (1K res)
- [ ] find cheaper programming head
- [ ] add bulk capacitors from controller

**Comment by taipingli** [comment]
Currently not doing due to cost reasons. Will reopen if needed in the future.

**Pull request closed without merging**
