### PR TITLE
ELEC-304: Lights Schematic

### PR DESCRIPTION
**Pull request by veroniclee**
Revision 1.2 
Schematic library: added 1K resistor array
PCB footprint: added 1K resistor array (Note: footprint for resistor
array looks strange/is it correct?)

- Fixed schematic for high side driver
- Fixed LEDs (not sure how to add jumpers to disable LEDs)
- Changed everything so GND on bottom and 12V on top
- Made names more descriptive

### CODE REVIEW

**Comment by taipingli** [comment]
Schematic: 
- [ ] Either update, or replace the quad HSD schematic symbols. They don't seem to be updated in the schematic itself despite being updated in the library 
- [ ] Flip the connector so pin 1 is on top (Control click to drag away from the schematic, then y to flip)
image
- [ ] Add a jumper going between 12V and LED_12V. If this jumper is removed, then none of the LEDs are powered. If the jumper is used, the LEDs switch according to the mosfets. Check power distribution for the 2 pin 0.1" jumper used. 
- [ ] Flip the 12V symbols so they face up like below (Control click to drag away, then space to rotate)
image
- [ ] Copy the correct harness for the headlight from the Controller Board Interface Sheet and replace this on Lights 2 
- [ ] Rename Lights and Lights 2 to something more descriptive. E.g. MSXII_Tail_Lights, MSXII_Headlights
image

**Comment by tituschow** [comment]
For context: Initial review comments:

- [ ] Make project file names more descriptive
- [x] Try to make grounds vertical
- [x] Combine parallel load nets with a wire
- [x] Use resistor network instead of a bunch of 1ks
- [x] Fix LED outputs
- [ ] Change your net names to be more descriptive (mezzanine)
- [ ] Add jumper to disable LEDs
- [x] Make sure drain is on top, source is on bottom
- [x] GND should always be facing down
- [x] Organize schematic
- [x] Make sure 12V LEDs are not too bright
- [ ] High side driver schematic symbol: Don't need part number, move Vcc to top, fix designator, check pin numbers - usually go anticlockwise, add thermal pad to symbol

**Comment by taipingli** [comment]
Apologies if I wasn't clear. Let's add 1 jumper in total. So this jumper has 12V on one side, then LED_12V on the other side. LED_12V goes to the 10k resistor which then goes to the led and into the FET. 

Also, please make sure that everything, including the pins on the schematic symbol is aligned on a 10mil grid (G to cycle through grids)
image

**Comment by tituschow** [comment]
We need to remember to have a jumper or something to mark whether the board is front or back. Maybe a switch with an LED?

**Comment by tituschow** [comment]
- [ ] Put port/pin back on the mezzanine nets
- [ ] Make sure font sizes are all the same
- [ ] Try to keep alignment uniform
- [ ] Fix dual package FET
- [ ] Use directives for high current
- [ ] Double check thermal pad
- [ ] Fix silkscreen font size
- [ ] Use polygon pours for high current paths
- [ ] Need 12V connector for power in
- [ ] Need to add GPIO input (jumper or switch) with LED to determine front/back
- [ ] Use resistor array for LEDs?
- [ ] Add silkscreen to everything - what the LEDs for, connectors
- [ ] Add silkscreen for board name
- [ ] Look into VN3050

**Comment by tituschow** [comment]
- [ ] Lines separating sections seem to be slanted - try holding shift while drawing the line
- [ ] For net names going to the controller board, you can rename them to more descriptive names as long as you keep the port/pin. For example, replace `PB10/USART3_TX/I2C2_SCL` with `PB10/FRONT_LIGHT_NAME/REAR_LIGHT_NAME`
- [ ] Increase your title font sizes and try to keep them in the upper-left corner of each box
- [ ] Since we're using nfets for everything, all our other lights are active-low. We might as well use an active-low load switch as well. It doesn't really matter, but it's just more consistent.
- [ ] Vcc for the load switch is the logic-level supply - this should be 3v3.
- [ ] Double-check if the default slew rate on the load switch is good for our use.
- [ ] Why do all of the GPIOs have pull-downs? I don't think the ones for the load switches need them since the load switches have internal pull-up/down resistors. @taipingli any thoughts? I noticed that you have them on power distribution as well.

**Comment by tituschow** [comment]
- [ ] I'm pretty sure that the LEDs for your load switches should be reversed - VOUT -> LED -> GND
- [ ] Please update your schematic titles
- [ ] Please change the name of your PcbDoc
- [ ] Could you label your jumpers on your schematic? I wasn't sure what the purpose of JP2 was until I thought about it.

**Comment by taipingli** [comment]
Let's leave the connectors separate. It'd make the harness easier to make and route

**Comment by tituschow** [comment]
- [ ] Please remember to rename your titles and update your revision.
- [ ] Make sure you're using thicker traces/polygons for high current connections. I see a few places where you aren't doing that. I also see some places where the connector via is only half in the polygon.
- [ ] Right now, we aren't really taking advantage of the board size. From what I can see, there isn't a huge benefit from using a large 4-layer right now. It seems like you should be able to move to a smaller 2-layer.
- [ ] Label your connectors, each pin, LEDs, etc. You want to be able to use this board without having to open the schematic to figure out how these should be plugged in. Similarly, making it obvious what configuration front/back should have. Is it front when the jumper is on or off?
- [ ] Label your connectors and jumpers in the schematic. I currently have no idea what JP2 is for. It just seems to turn an LED on.

What does DNP capacitor on SR mean?

@taipingli Are hazards separate lights or are we sharing the turn signal lights again?

**Comment by taipingli** [comment]
- [ ] Flip D1 so it's normally reverse biased (not conducting), and only conducts when the horn is switched off
image
- [ ] Move D1 so it's closer to the connector. 
image
- [ ] Make sure silkscreen is aligned, and capacitor silkscreens aren't too close to the pads
image
- [ ] Also update the footprint for the loadswitch from the library. I added a 3D model. To do this, go to the component in PcbLib, Tools, update pcb with current footprint and use the default settings. 
- [ ] Seems like the 12V and GND vias have thermal relief on them in the internal planes. Add a rule as "Not(isPad)" or something like that in the power plane connect style under rules.

**Comment by tituschow** [comment]
I believe this is still missing a block diagram and table. We can move that to a new PR.

**Pull request merged**
