### PR TITLE
ELEC-222 Motor Interface Schematic

### PR DESCRIPTION
**Pull request by Grenite**
Added initial schematic and PCB files to project folder. PCB board is withing a 5x5 cm layout.

### CODE REVIEW

**Comment by Grenite** [comment]
- [ ] Rotate ultra-fit connectors 180 degrees
- [ ] Remove the 3V LDO, VDDA can be powered by 3V3
- [ ] Remove the Debug LEDs
- [ ] Move the CAN transceiver to be in between the CAN connectors
- [ ] Remove the low speed oscillator
- [ ] Move the MCU away from the controller board
- [ ] The MOSFETs should be controlled by the controller board
- [ ] Move the decoupling caps closed to MCU
- [ ] Reorganize and realign components for neatness and less cutup GND plane

**Comment by tituschow** [comment]
- [ ] This should be set to 90 degrees to fix your thermals
image
- [ ] Rename nets, silkscreen, etc for the precharge left/right instead of 1/2
- [ ] Align silkscreen and components to 10 mil grid where possible (for example, this looks pretty messy)
image
- [ ] Update your board name silkscreen
- [ ] Add pinout silkscreen
- [ ] Try to avoid sharp/unnecessary turns

**Comment by tituschow** [comment]
P5 is not aligned with the rest of the connectors
Are you sure you aligned your components and silkscreen? Everything still looks kinda funky.
image
Move J1 down so the silkscreen is more readable. In general, try to make the silkscreen readable and it helps if you keep its position consistent (for example, try to keep them centered or to the side) - The align tools are very helpful for this, especially "align centers"

**Comment by taipingli** [comment]
For the connections to the FETs, let's use polypours instead of traces. Also, the last time we observed that the relays themselves inject a decent amount of noise back into the 12V rail, so it might be good to move things a bit further from them. 

- [ ] Move PA13's trace near the microcontroller such that you can get a bit more ground plane for ground pin. You could then put maybe 2 vias there. 
- [ ] Put bulk caps on the 12V rails to the precharge controllers, as there will be a large instantaneous current draw when switching
- [ ] Put pull downs on the sense lines of the relays, 10k should be fine
- [ ] Fix the ground connection to U2 pin 8, if you move the 3v3 line down a bit you might be able to get a via under U2
- [ ] Make the vias on the GND of the FETs powering pre-charge larger (Make sure it can handle 1A continuous, 3A peak each)

**Comment by taipingli** [comment]
@tituschow Do we want any termination resistors for CAN on this? Would that make things easier for the motor controller side?

**Comment by tituschow** [comment]
No, the termination resistors should be at the ends of the bus. The way we're placing connectors on this looks more like this board is in the middle of the bus.

**Comment by Grenite** [comment]
@taipingli when you say "Sense lines of the relays" do you mean the gates of the MOSFETs? Or is it simply just the Sense lines on the precharge controller?

**Comment by tituschow** [comment]
- [ ] Update project lead
- [ ] Update schematic templates
- [ ] Update 3D model of controller board
- [ ] Don't disable thermals for all GND connections
- [ ] Add decoupling caps between relay GND and 12V to combat noise
- [ ] The loop for the 10k pullups seems excessive and cuts your ground plane quite a bit

**Comment by tituschow** [comment]
- [ ] Name nets
image
- [ ] Align connectors
image
- [ ] Align grounds and push the whole thing up a bit so it isn't touching the edge
image
- [ ] Label this
image

**Comment by taipingli** [comment]
ELEC-294 will supersede this PR.

**Pull request closed without merging**
