### PR TITLE
ELEC-401: Charger Can Interface Board

### PR DESCRIPTION
**Pull request by ArshanKhanifar**
Added proximity detection and control pilot circuits.

### CODE REVIEW

**Comment by ArshanKhanifar** [comment]
- fix schematic text size orientation etc
- make a table explaining the states
- switch mcu peripherals to controller board interface
- VDD connected to 3v3??
- proximity circuit be clamped to 3v? voltage divider and buffer
-  dont care about level so bring a level shifter? from 12v to 3v?
- add a relay

**Comment by menalabib** [comment]
Fix PA08/TI'N' on controller interface
Consistency in controller interface
Add current limiting RES on charger relay EN
Separate CAN networks
add descriptions on connectors
add chip name to U5
add state table for control pilot
fatten up traces 
clean bottom layer traces

**Comment by taipingli** [comment]
Let's change the microcontroller + CAN transceiver to a MCP2515 similar to motor controller interface. The CAN to UART translation did not work as well as we expected and we're falling back to what we had in the last car. No changes should be necessary for interfacing with the charger, but we have to decide on whether or not to use an onboard HV relay for charging.

**Comment by plguo** [comment]
I have started the work to add the MCP2515 to the motor controller interface. I am considering either apply the same chip change to the charger interface or using board variant to merge the charger interface and motor interface.

**Comment by taipingli** [comment]
I think whether or not we want to use the board variants depend on how we want to handle the relay. It might make sense to run HV directly on the board (downside is isolation and making sure we can carry enough current), but it would simplify wiring significantly. The charger interface would also have different connectors and need isolation for some things so it might make sense to keep them separate?

**Comment by plguo** [comment]
In that case, separate board is better option. I have the MCP2515 schematic and footprint on my branch. If you need any help, let me know.

**Comment by taipingli** [comment]
Tagging @menalabib and @ArshanKhanifar. Let's try and send this out by this Sunday afternoon. @plguo , I'd prefer it if you can work on solar stuff since the array is going on around the 23rd, so realistically we have to get solar sense master and slave out this weekend if possible.

**Comment by taipingli** [comment]
This board has been merged with the Motor Controller Interface, PR will be closed.

**Pull request closed without merging**
