### PR TITLE
ELEC-214 Steering Wheel PCB

### PR DESCRIPTION
**Pull request by Grenite**
Initial draft of the PCB open for review.

### CODE REVIEW

**Comment by taipingli** [comment]
July 13 Board Review
- [ ] Use the same location for all buttons
- [ ] Add 0 Ohms if necessary
- [ ] Caps for all labels 
- [ ] Add right angle headers instead
- [ ] Move mounting points 
- [ ] Try importing it into solidworks to fit the steering wheel
- [ ] Reduce the size to below 10x5cm

**Comment by Grenite** [comment]
- [ ] Fix the turn indicator buttons that are not flipping in the variants
- [ ] Reduce board size even more

**Comment by taipingli** [comment]
- [ ] Make board outline match the steering wheel
- [ ] Make silkscreen the same size
- [ ] Caps for all silkscreen on botton

**Comment by taipingli** [comment]
It's unclear at the moment if we will be using stalks or purely buttons on the steering wheel. This will be on hold until that's decided.

**Pull request closed without merging**
