### PR TITLE
HW-82 Pedal Board Rev 3

### PR DESCRIPTION
**Pull request by aashmikamali**

### CODE REVIEW

**Comment by plguo** [comment]
The schematic looks good to me. Just remember update the revision number in the schematic.

**Comment by plguo** [comment]
The PCB layout and routing are mostly good. Just some notes for future designs.
- Consider using polygon pours more often to connect power planes (3V3 & 12V) and multiple pads with the same net
image

- Altium is already automatically connecting the pads to the vias. So it is not necessary to manual draw another path to the vias
image
image

- Once you finish the layout, remember to add the controller board model back to check the clearance
- It is always a good idea to add test points to your board for debugging

I updated the footprint of the dual op-amps ICs. Remember to double check the footprint and don't be me 😬.

**Comment by taipingli** [comment]
@plguo Was the footprint for the dual-opamp the only part that you changed in the libraries for both the pedal and steering interface board?

**Comment by plguo** [comment]
Yes. Is there any other new part in this PR?

**Comment by taipingli** [comment]
Ok, I'm going to add the footprint to the center console board, merge that, and then use that library for this and the steering interface branch then.

**Comment by plguo** [comment]
Why not merge #77 first? It has the updated op-amp footprint.

**Pull request merged**
