### PR TITLE
ELEC-301: IMU Board Schematic & PCB

### PR DESCRIPTION
**Pull request by gmardari**
This revision includes:
-IC IMU Sensor
-SPI interface
-Temperature sensing

### CODE REVIEW

**Comment by taipingli** [comment]
Schematic: 

- [ ] Could you try and reorganize the schematics a bit? If it helps, you can also divide it up into sections (check controller board as an example)
- [ ] Add a low pass RC filter to the temperature. I suggest adding a unity-gain buffer to prevent any issues from the ADC and the leakage current into the pins. You can also add the buffer, and also add a 0 ohm resistor to bypass it and go straight into the RC filter so we can test both and see if there's any differences. But having it on the board is a lot easier than having to spin a new board. 
- [ ] If you're using SPI, add test points to all the SPI lines (NSS and SCK too)

PCB:
- [ ] Make the 12V trace thicker (15 - 20mil) 

@gmardari @tituschow  Do we want the ability to use a off the board thermistor as well? In case there's any specific component or something that we want to sense that isn't ambient temp.

**Comment by tituschow** [comment]
- [ ] Add off-board connector for thermistor (default DNP)
- [ ] Partition schematic into zones (see controller board for example)
- [ ] CS net not connected on the PCB
- [ ] Update rev # on the board
- [ ] Add keepout around the whole board

**Comment by tituschow** [comment]
Please check off things as you get them done.

- [ ] Fix the LDO designator and visible parameters - you don't need the digikey part number
- [ ] Please add default values to your RC @taipingli ?
- [ ] Your external thermistor connector is confusing. Please rearrange your schematic so that it isn't wrapped around another block.
- [ ] All analog rails should be powered by the LDO.
- [ ] Please make sure your polygons are showing before committing so we don't need to reenable them.
- [ ] You need to make sure to update your PCB with your schematic changes - I don't see the thermistor connector
- [ ] The IMU ground pins seem a little cut off - I would probably add some vias to punch the ground plane from the mezzanine through to the bottom layer after your 3v3 trace and connect all the ground pins together.
- [ ] If you move the 3v3 traces around a bit, I think you can improve your bottom ground plane.

**Comment by tituschow** [comment]
- [ ] Move the LDO the power section
- [ ] All analog should be powered off LDO
- [ ] Don't put all the test points in test point area
- [ ] Move the thermistor connector so that the power rail is above
- [ ] Add text explaining this is an external thermistor
- [ ] Use actual thermistor symbol - see DC-DC
- [ ] Use RT? for thermistor designator
- [ ] Silkscreen connectors, test points

**Comment by tituschow** [comment]
Just so you know, your bottom ground plane on the LV side isn't very useful right now because it's cut by the 3V trace.

- [ ] Add silkscreen for each pin of the connector - see power distribution for example
- [ ] Move board name silkscreen so that it's visible when the controller board is on top

**Comment by tituschow** [comment]
Looks pretty good, just some minor comments:

I'd probably add some text on the schematic explaining the purpose of P3 - something along the lines of DNP R6 to use the external thermistor.

Just for cleanliness, I would not have the `LDO_3V` power port off on the left in the power section. It would look a little nicer if it was similar to the `3V3` power port. That's just a style thing though.

Similarly, you can move your temp sense circuit so that it fits on the page a little better. Right now it seems very squished, especially because it's right against the title (it would be nice if the titles were aligned horizontally as well)

- [ ] Please remember to update your schematic revision numbers.

PCB:
- [ ] Please label TP5 and TP6
- [ ] Align TP3 and TP4 silkscreen

For the board size, our intention was to standardize on 5x5 boards, but you aren't using that space at all. @taipingli Thoughts on this? Increase the height or just keep it small?

**Comment by taipingli** [comment]
Couple of minor changes to routing: 
- [ ] Move the decoupling cap C3 closer to the op amp. Recommend doing something like this
image
- [ ] Move the LDO output capacitor closer by and redo the routing in that area. Note the shorter path from pin 1 to 4 on the op amp, and the more direct path from LDO_3V to the capacitor then to the component 
image
- [ ] Have better ground for the IMU IC. something like this
image
image

Otherwise I think it looks good. Be sure to run a design rule check when you're done to check for any unrouted connections or net antennae (dead traces not connected to anything).

**Pull request merged**
