### PR TITLE
ELEC-161 Finished Schematic for Chaos, Library additions for all components

### PR DESCRIPTION
**Pull request by taipingli**
Finished schematic for Chaos. Added the following parts to schematic library. All components used should also have an associated footprint. 3D models have been added whenever possible. One more schematic review is scheduled for May 27, but no major changes are expected. 

Schematic Library Additions: 
- RES 4.7K OHM 1% 0603
- LED YELLOW 0603
- IC OP AMP GEN PURPOSE RR 10MHZ (TI TLV316) for buffers

Footprint Library Additions: 
- CAP ALUM 100UF 50V
- CONN 2POS ULTRA-FIT NATURAL COLOR
- CONN 6POS ULTRA-FIT
- FUSE ATO/ATC FUSE HOLDER
- IC CURR SENSE AMP 80KHZ
- IC GEN PURPOSE RR OP AMP
- IC OR CTRL SRC SELECT (POWERPATH IC) 
- MOSFET N-CH MOSFET 30V 12A 2mmx2mm PQFN
- RES 2010

### CODE REVIEW

**Comment by KevinHQChen** [comment]
@taipingli why 5 mil grid?

**Comment by taipingli** [comment]
@KevinHQChen Mainly so that components can be made on a 5 mil grid without being excessively large. Also a good balance of spacing between things.

**Comment by KevinHQChen** [comment]
@taipingli Still seeing a lot of off-grid components:
image

Don't connect net labels to wires using the electrical grid:
image
This is dangerous and can result in unconnected nets. Use the snap grid instead. (https://uwmidsun.atlassian.net/wiki/display/ELEC/Basic+Concepts - read the grid section)

Please stick to one convention for connecting net labels, I suggest the first one:
image
image

Pin 6 on this component CONN '6POS ULTRA-FIT 0.138"' is off-grid, please fix it in the SchLib.
image

**Comment by taipingli** [comment]
Schematic should now be complete for Power Distribution. Rev 1.5 had minor aesthetic changes as well as changes to the schematic library. The resistor divider values going into the PowerPath IC were tweaked for a 12V DCDC (±1%), and 9-13.5V 9s Ni-MH auxiliary battery with a 1V threshold. Detailed calculations will be posted on Confluence soon.

**Pull request merged**
